[package]
name = "axum-playground"
version = "0.1.0"
edition = "2018"

[dependencies]
axum = "0.2.3"
tokio = { version = "1.9.0", features = ["full"]}
tracing = "0.1.26"
tracing-subscriber = "0.2.19"
serde = { version = "1.0.127", features = ["derive"]}
serde_json = "1.0.66"
